# Generated by Django 3.2.8 on 2021-10-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=200)),
                ('whitelist', models.CharField(max_length=200)),
                ('product_xpath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PSAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_xpath', models.CharField(max_length=200)),
                ('ps_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productscraper.psconfig')),
            ],
        ),
    ]
