# Generated by Django 3.2.8 on 2021-10-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psconfig',
            name='whitelist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
